#! /bin/bash

#  aws cloudfront create-invalidation --distribution-id E3L4RITZ2SYT0U --paths /favs.html /fav2.html /fav3.html
   aws cloudfront create-invalidation --distribution-id E3L4RITZ2SYT0U --paths /index.html /index3.html /assets/dan/* 

