#! /bin/bash

./htmlmod2
git add .
echo "What changes?"
read ans 
git commit -m "$ans"

echo pushing to git origin,  git.dfwskyview.com
git push origin

echo
echo
echo after some time, confirm at http://git.dfwskyview.com
