#!/bin/bash

mybase=skyview

cd ~/Documents/aws/$mybase

# Add stuff into the html
./htmlmod

# Cant use --delete here since there are multiple source locations
# --exclude fails, so move git

# Sync basic web content
#mv .git ../dfw_git
echo Sync basics to s3.dfwskyview.com
aws s3 sync  ~/Documents/aws/$mybase  s3://s3.dfwskyview.com/  --acl public-read 
#mv ../dfw_git .git

# Sync media and zip files too
echo Sync media to s3.dfwskyview.com
aws s3 sync ~/Movies/dfwskyview/samples s3://s3.dfwskyview.com/samples  --acl public-read --cache-control max-age=31536000,public


echo Maybe do zip -r ../${mybase}45.zip .
echo Maybe run ./invalidate after review on s3.
