#!/bin/bash

mybase=skyview
today="`date '+%m%d%Y'`"

cd ~/Documents/aws/$mybase

# Add stuff into the html
./htmlmod

# Cant use --delete here since there are multiple source locations
# --exclude fails, so just move git

# First back it up
echo; echo backing up current in 3..........................
sleep 3
aws s3 sync s3://s3.dfwskyview.com/ s3://last.dfwskyview.com/${today} --acl public-read 
aws s3 sync s3://s3.dfwskyview.com/ s3://last.dfwskyview.com          --acl public-read 


# Sync basic web content
mv .git ../${mybase}_git
echo Sync pages to s3.dfwskyview.com
aws s3 sync  ~/Documents/aws/$mybase  s3://s3.dfwskyview.com/  --acl public-read 
mv ../${mybase}_git .git

# Sync media and zip files too
echo Sync media to s3.dfwskyview.com
aws s3 sync ~/Movies/dfwskyview/samples s3://s3.dfwskyview.com/samples  --acl public-read --cache-control max-age=31536000,public


echo Maybe do zip -r ../${mybase}45.zip .
echo Maybe run ./invalidate after review on s3.
